### PR TITLE
Fix compile errors for DMD 2.068.0

### PR DESCRIPTION
**Pull request by jacob-carlborg**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
@SiegeLord ping. Are you still maintaining this project?

**Comment by SiegeLord** [comment]
Whoops, this somehow slipped my radar. I'll check this out asap.

**Comment by SiegeLord** [comment]
Merged as 94beff1366be3aab8204e1f1b5603f94aa2169cc. Thanks!

**Comment by jacob-carlborg** [comment]
Thanks.

**Pull request closed without merging**
