### PR TITLE
Some fixes for dmd v2.060

### PR DESCRIPTION
**Pull request by IgorStepanov**
I've commented extern function rt_isHalting(); (It's a part of old tango runtime and does not exists in druntime), and add some casts to non-const types.

### CODE REVIEW

**Comment by SiegeLord** [comment]
Could you look at https://github.com/SiegeLord/Tango-D2/tree/2.060 and see if you do anything extra relative to that ? I put the 2.060 things into a separate branch because many of them are backwards incompatible with 2.059.

**Comment by IgorStepanov** [comment]
http://pastie.org/4467974

**Comment by fawzi** [comment]
I hadn't seen this, so I hacked in some fixes, in some places in really ugly way (casting away const instead of propagating it), but it works without errors, so it might be useful as comparison. I hadn't the time to compare with what was done here, I might look at it later if I have the time, anyway here are my hacks http://pastie.org/4474703

**Comment by SiegeLord** [comment]
Ok, so I manually merged most of the new commits. I deleted the 2.060 branch and made a 2.059 branch. d2port branch is now for the 2.060 DMDFE compilers.

Now... about 21657ca7fe78e91680d004b7efb0942a1296545a ... Igor, could you explain what's the deal with the stdio/stdlib/string changes? Of the ones I tried looking for all those functions are documented at MSDN... is this some DMD'ism?

**Comment by IgorStepanov** [comment]
This functions don't exist in DMD/DMC libraries.
If you've tried to call this funtions under Windows DMD, you will get a "undefined reference ..." message.
P.S. Sorry for the long absence.

**Pull request closed without merging**
