### PR TITLE
Remove more pragma(msg) outputs for Windows

### PR DESCRIPTION
**Pull request by jacob-carlborg**

### CODE REVIEW

**Comment by SiegeLord** [comment]
Hmm, you sure about that? This converts a warning to an error on Windows?

**Comment by jacob-carlborg** [comment]
> Hmm, you sure about that? This converts a warning to an error on Windows?

Not entirely. But Unix sockets doesn't exist on Windows. Not sure what happens if this is used on Windows.

**Comment by jacob-carlborg** [comment]
Do you prefer that I convert the pragma into a comment instead? Or perhaps use `deprecated`?

**Comment by SiegeLord** [comment]
Nah, I think this makes sense. If this never worked, the downstream code would already be versioned to handle this; this change just moves the version upstream, which should be okay.

**Comment by SiegeLord** [comment]
Thanks!

**Pull request merged**
