### PR TITLE
Fix `tango.text.Regex` compilation on latest dmd.

### PR DESCRIPTION
**Pull request by denis-sh**

### CODE REVIEW

**Comment by SiegeLord** [comment]
Why is the `opCmp` removed? Does it cause a compilation error or something or is it merely unnecessary?

**Comment by denis-sh** [comment]
Yes, it causes errors:

``` D
struct S
{
    int opCmp(S) const;
}

void main()
{
    int[S] s;
}
```

```
main.d(8): Error: AA key type S now requires equality rather than comparison
main.d(8):        Please define opEquals, or remove opCmp to also rely on default memberwise comparison.
```

Also one should be very careful, as old build-in `sort` doesn't issue a compilation error and just throws at runtime if `opCmp` isn't defined.

**Comment by SiegeLord** [comment]
Ok. Would you mind, instead of removing it, wrapping it in `static if(DMDFE_Version == 2065) {}` ? You'll need to import the `tango.core.Compiler` module.

Also, I get a segfault when I run the unittests in this module:

```
.unittest/out(_D4core7runtime18runModuleUnitTestsUZb19unittestSegvHandlerUiPS4core3sys5posix6signal9siginfo_tPvZv+0x3e)[0x46d4da]

#0  0x000000000046ccc4 in rt.typeinfo.ti_void.TypeInfo_v.getHash() ()
#1  0x0000000000463423 in object.TypeInfo_StaticArray.getHash() ()
#2  0x0000000000443572 in tango.text.Regex.__T4TDFATwZ.TDFA.Command.toHash() ()
#3  0x0000000000464342 in object.TypeInfo_Struct.getHash() ()
#4  0x0000000000465524 in _aaGetX ()
#5  0x0000000000447038 in tango.text.Regex.__T4TDFATwZ.TDFA.reorderTagIndeces() ()
#6  0x0000000000465d2a in _aaApply2 ()
#7  0x0000000000446ca7 in tango.text.Regex.__T4TDFATwZ.TDFA.reorderTagIndeces() ()
#8  0x0000000000444b7b in tango.text.Regex.__T4TDFATwZ.TDFA.__ctor() ()
#9  0x000000000045880e in tango.text.Regex.__T4ListTC5tango4text5Regex11__T4TDFATwZ4TDFA11SubsetStateZ.List.opApply() ()
#10 0x0000000000444674 in tango.text.Regex.__T4TDFATwZ.TDFA.__ctor() ()
#11 0x0000000000440256 in tango.text.Regex.__T7RegExpTTaZ.RegExpT.__ctor() ()
#12 0x000000000044017e in tango.text.Regex.__T7RegExpTTaZ.RegExpT.__ctor() ()
#13 0x000000000043f918 in tango.text.Regex.__unittestL4748_2() ()
#14 0x0000000000459f96 in tango.text.Regex.__modtest() ()
#15 0x000000000046d55c in core.runtime.runModuleUnitTests() ()
#16 0x000000000046a860 in rt.minfo.moduleinfos_apply() ()
#17 0x000000000046a956 in rt.sections_linux.DSO.opApply() ()
#18 0x000000000046a7f9 in rt.minfo.moduleinfos_apply() ()
#19 0x000000000046d3f2 in runModuleUnitTests ()
#20 0x0000000000466c0b in rt.dmain2._d_run_main() ()
#21 0x0000000000466bbe in rt.dmain2._d_run_main() ()
#22 0x0000000000466b3f in _d_run_main ()
#23 0x000000000043e82f in main ()
```

I am guessing that strange `typeid` trick you added isn't quite working right?

**Comment by denis-sh** [comment]
Thanks, I'll investigate and fix the pull in a couple of days.

**Comment by SiegeLord** [comment]
Tango now compiles without these changes (but see #78). Thanks!

**Comment by denis-sh** [comment]
Sorry for being silently unavailable for such a long time. (
Thanks for resolving the problem!

**Pull request closed without merging**
