### PR TITLE
better build system who support all compiler

### PR DESCRIPTION
**Pull request by bioinfornatics**
Hi,
I have written some makefile for support:
- all compiler
- no harcoded source filename
- support multithread with -j flag

TODO: add build doc

### CODE REVIEW

**Comment by bioinfornatics** [comment]
one thing i have miss move tango directory at root project in src directory

**Comment by SiegeLord** [comment]
I have 3 issues with this:
1. It doesn't work right now because not all the modules have been ported
2. Once they _are_ all ported, we'll have the bob build system working just like in the normal Tango
3. This is not D2 porting related, so it should go into the main Tango repository. It will then get into TangoD2 when TangoD2 syncs with the main development branch.

**Comment by bioinfornatics** [comment]
- with makefile you build .o only if needed
-  dynamically each source in each package (not hardcoded)
- multithread
- support ldc, gdc and dmd

**Comment by bioinfornatics** [comment]
about src "for me" is more clearh
documentaion in his in dir
source ...
build ....
"for me" the root project is more easier for find where search (what conatins each dir)

**Pull request closed without merging**
