### PR TITLE
Pull Request after Rebase

### PR DESCRIPTION
**Pull request by mtachrono**

### CODE REVIEW

**Comment by SiegeLord** [comment]
I'm a little confused, why does this include all of my commits too? Shouldn't it include only your commits?

**Comment by mtachrono** [comment]
I'm also confused.. When I forked your project, I recognized that your master branch if very old. All the changes you made are only included in your siege_tangod2 branch. Therefore I merged your siege_tangod2 branch with my fork. Maybe you should first merge your branch with master and then I should rebase on that???

**Comment by SiegeLord** [comment]
Hmm. The master branch is set to follow the Tango SVN repository, and I rebase my siege_tangod2 branch on it periodically.

**Comment by mtachrono** [comment]
I didn't know that. That's the REASON why I got really really strange errors, because everytime you rebase siege_tangod2 on master my fork (which includes stuff of siege_tangod) points to /dev/urandom.

You have to keep in mind that rebasing means to change the history of your repository. Everybody who has a fork (like me) will have difficulties to keep sync with you.

**Comment by SiegeLord** [comment]
Right, but there's really no other clean way to follow the Tango SVN otherwise (that I know of). If I merge the SVN commits into my siege_tangod2 branch, then I'll get commits that are not really related to the porting effort.

I am guessing the solution would be for us both to rebase on the Tango SVN (my master) periodically, and then merge between our offshoot branches (my siege_tangod2 and your master).

Tell me if you have better ideas.

**Comment by mtachrono** [comment]
Puh.... I think it's time that tango D2 get's his own history. I don't like to just port it, I think active development is better. There are so much changes between D1 and D2, and a long time ago there wasn't any druntime. I'm using tango side by side with phobos.

But I understand if you don't agree. Feel free to say your opinion.

**Comment by SiegeLord** [comment]
Yeah, I don't agree with doing more than just porting it (at least myself). Still, I don't want to prevent people who want to do so (like yourself) from doing so. I guess I'll just do normal merges into my siege_tangod2 branch from now on, this way there shouldn't be any more history rewrites.

**Comment by mtachrono** [comment]
Would it be possible if you rename your master branch to svn, which acutally only syncs the the tango svn repository. Then you could create a new fresh master branch which is the basis for all tango D2 development. Everybody could fork that master, and submit his or her pull requests to it meanwhile your svn branch follows the svn repository and you could focusing on porting. And peu a peu, we merge your porting stuff to master.

-> svn branch: follows tango's svn
-> master branch: main tango d2 development
-> siege_tangod2 branch: only porting related

**Comment by SiegeLord** [comment]
Why do I need a branch specifically for non-porting D2 development (as I'm not doing it personally)?

I'm thinking something like this:
-> master: porting efforts
-> svn: follows the svn

**Comment by mtachrono** [comment]
As you told me one day, you'd like to own the primary repository of tango d2 development.

**Pull request closed without merging**
