### PR TITLE
Ported most of the remaining modules.

### PR DESCRIPTION
**Pull request by IgorStepanov**
All modules compile successfully under Linux32.

### CODE REVIEW

**Comment by SiegeLord** [comment]
Wow. Nice work.

It'll take me awhile to get through all of this, but I already can see some things that I'd appreciate you fixing to help me with it:
1. Some files seem to be entirely rewritten (e.g. tango/core/tools/Cpuid.d), which is indicative of a line ending change. I know that occasionally that's an issue in the original code, but I'd rather fix it in a separate commit. Could you please revert those files to their orignal line endings?
2. What is the cstring thing all about? I'd prefer it to be const(char)[] for consistency. We're not shooting for D1 support anyway, so its unnecessary if that was the reason for its use.

Thanks!

**Comment by apriori** [comment]
I've got a build issue with this on 64bit dmd linux

## object.Exception@../Tango-D2/build/src/bob.d(641): Process exited normally with return code 1

./build/bin/linux64/bob(char[] bob.Linux.compile(tango.io.FilePath.FilePath, const(char)[])+0xc1) [0x433dd1]
./build/bin/linux64/bob(int bob.Linux.dmd()+0x1b8) [0x433f98]
./build/bin/linux64/bob(_Dmain+0x13e) [0x4335da]
./build/bin/linux64/bob(extern (C) int rt.dmain2.main(int, char**).void runMain()+0x17) [0x45367f]
./build/bin/linux64/bob(extern (C) int rt.dmain2.main(int, char**).void tryExec(scope void delegate())+0x2a) [0x453226]
./build/bin/linux64/bob(extern (C) int rt.dmain2.main(int, char**).void runAll()+0x42) [0x4536d2]
./build/bin/linux64/bob(extern (C) int rt.dmain2.main(int, char**).void tryExec(scope void delegate())+0x2a) [0x453226]
./build/bin/linux64/bob(main+0xd3) [0x4531b7]

## /lib/libc.so.6(__libc_start_main+0xed) [0x7f6e63b4d38d]

tango.io.FileScan is deprecated. Please use tango.io.FilePath.toList or tango.io.vfs.\* instead.
./tango/io/stream/Data.d(349): Error: function tango.io.stream.Data.DataOutput.int32 (int x) is not callable using argument types (ulong)
./tango/io/stream/Data.d(349): Error: function tango.io.stream.Data.DataOutput.int32 (int x) is not callable using argument types (ulong)
./tango/io/stream/Data.d(349): Error: cannot implicitly convert expression (len) of type ulong to int
./tango/io/stream/Data.d(351): Error: cannot implicitly convert expression (len) of type ulong to uint

I don't know how to fix that properly, since I don't know whether DataOutput is supposed to write the exact same output on 64bit and 32bit or not.

**Comment by IgorStepanov** [comment]
We may put array length as int64.

**Comment by SiegeLord** [comment]
I had to change quite a few things after merging it. Here are a few things to keep in mind:
1. Tango uses spaces for indentation, not tabs
2. Watch out for trailing whitespace
3. Compile with unittests enabled (-unittest -debug -debug=UnitTest) because templates classes don't get checked for semantic errors unless they are instantiated (and oftentimes they are only instantiated in unittests)

The other stuff that I changed was questionable, but I just don't like how you did some things :P. I am open to changing them back (I'll add a few tickets about it in a moment).

Thanks again for all the effort!

**Pull request merged**
