### PR TITLE
Makefile

### PR DESCRIPTION
**Pull request by bioinfornatics**
- automatic search for source file by platform
- // build allowed by using -j <number> make's flag
- build as static / shared lib 
- able to generate native documentation (not dil, we could use ddoc file to have a better doc)
- generate package config file for allow easy link to others app / lib who use tango
- easy install
- rebuild .o file only if necessary

``` bash
$ ldc myProject.d $(pkg-config --libs --cflags tango)
```

### CODE REVIEW

**Comment by SiegeLord** [comment]
It turns out that the --- is a bug in the current DMD. Could you remove that particular commit from this pull request?

Also, on the topic of documentation, tango has a special version statement to make documentation prettier. Could you specify the version: 'TangoDoc' during the documentation building process? Yes, I know it won't build (probably my fault) but I'll fix it later.

**Comment by bioinfornatics** [comment]
they are a link to this bug somewhere?

**Comment by SiegeLord** [comment]
http://d.puremagic.com/issues/show_bug.cgi?id=7383

**Comment by bioinfornatics** [comment]
great, i will revert it

**Comment by bioinfornatics** [comment]
--- i have revert the commit and now you can run make from the build dir

```
$ make -f build/Makefile
```

**Pull request merged**
